server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: teacher-service
        uri: lb://teacher-service
        predicates:
        - Path=/teacher/**
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path="/student/**" 